# Generated by Django 2.0.4 on 2018-04-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('author', models.CharField(max_length=200, verbose_name='autor')),
                ('year_publication', models.PositiveIntegerField(blank=True, null=True, verbose_name='ano de publicação')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='editora')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
